apiVersion: v2
name: essential-invoice
description: A self-hosted invoicing application for Czech freelancers
type: application
version: 0.1.1
appVersion: "1.0.0"

home: https://github.com/vdovhanych/essential-invoice
sources:
  - https://github.com/vdovhanych/essential-invoice

maintainers:
  - name: vdovhanych
