import { useState, useEffect } from 'react';

/** MIME types we can render as an inline preview. */
export type PreviewMimeType = 'image/jpeg' | 'image/png' | 'application/pdf';

/**
 * Narrows a stored MIME type to one we can preview, returning a literal rather
 * than the input so no caller-supplied string reaches a URL.
 */
export function toPreviewMimeType(mimeType: string | null | undefined): PreviewMimeType | null {
  switch (mimeType) {
    case 'image/jpeg':
      return 'image/jpeg';
    case 'image/png':
      return 'image/png';
    case 'application/pdf':
      return 'application/pdf';
    default:
      return null;
  }
}

/**
 * Turns a base64 payload into an object URL for previewing.
 *
 * Preferred over a `data:` URL: the payload stays out of the markup (a data URL
 * embeds the whole base64 string in the src attribute and is re-parsed on every
 * render), and the resulting `blob:` URL is generated by the browser, so no
 * user-supplied text is interpolated into an element attribute.
 *
 * Returns null when there is nothing previewable. The URL is revoked when the
 * payload changes or the component unmounts.
 */
export function useObjectUrl(base64: string | null, mimeType: PreviewMimeType | null): string | null {
  const [url, setUrl] = useState<string | null>(null);

  useEffect(() => {
    if (!base64 || !mimeType) {
      setUrl(null);
      return;
    }

    let objectUrl: string;
    try {
      const binary = atob(base64);
      const bytes = new Uint8Array(binary.length);
      for (let i = 0; i < binary.length; i += 1) {
        bytes[i] = binary.charCodeAt(i);
      }
      objectUrl = URL.createObjectURL(new Blob([bytes], { type: mimeType }));
    } catch {
      // Malformed base64 — show the fallback rather than a broken preview
      setUrl(null);
      return;
    }

    setUrl(objectUrl);
    return () => URL.revokeObjectURL(objectUrl);
  }, [base64, mimeType]);

  return url;
}
