apiVersion: v1
kind: Service
metadata:
  name: {{ include "essential-invoice.frontend.serviceName" . }}
  labels:
    {{- include "essential-invoice.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "essential-invoice.frontend.selectorLabels" . | nindent 4 }}
