{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "essential-invoice.fullname" . }}
  labels:
    {{- include "essential-invoice.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.jwtSecret | b64enc | quote }}
  {{- if and (not .Values.postgresql.enabled) .Values.postgresql.external.password }}
  DB_PASSWORD: {{ .Values.postgresql.external.password | b64enc | quote }}
  {{- end }}
{{- end }}
